[platformio]
core_dir = ../../../.platformio-home
default_envs = m5stack-core-gray

[step-trigger]
lib = file://../../../calculator-face-input/packages/step-trigger

[env:m5stack-core-gray]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = m5stack-core-esp32
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = huge_app.csv
build_flags = -pipe
lib_deps =
  fcz2/amy-synth-m5@0.3.1
  fcz2/musical-clock@0.1.2
  ${step-trigger.lib}

[env:native]
platform = native
framework =
lib_deps = ${step-trigger.lib}
test_framework = unity
test_build_src = yes
build_src_filter =
  +<DrummerPresets.cpp>
  -<main.cpp>

